# Generated by Django 4.1.7 on 2023-03-31 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='название')),
                ('language', models.CharField(max_length=90, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='название')),
                ('place', models.CharField(max_length=90, verbose_name='место поездки')),
                ('time', models.TimeField(verbose_name='время поездки')),
                ('price', models.IntegerField(verbose_name='стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(max_length=20, verbose_name='скольки звёздная гостиница')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.CharField(max_length=90, verbose_name='тур')),
                ('time', models.TimeField(verbose_name='время поездки')),
                ('price', models.IntegerField(verbose_name='стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sevice', models.CharField(max_length=20, verbose_name='Сервис')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время прохождения')),
                ('countHuman', models.IntegerField(verbose_name='количество человек')),
                ('price', models.IntegerField(verbose_name='цена тура+экскурсии')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='Название страны')),
                ('excursions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.excursions', verbose_name='экскурсии')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hostel', verbose_name='Гостиница')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.privatecabinet', verbose_name='Название тура')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service', verbose_name='Сервис')),
            ],
        ),
    ]
